### ISSUE TITLE
* binds more tightly than implicit comma when specifying types

### ISSUE THREAD

**Issue by aualsop** [nyusemantics/LambdaCalculatorPublic#20]
When specifying the types of constants in exercise files, implicit commas should bind more tightly than *. Currently the opposite is the case. 

For example, the command `constants of type <e*st,st>: P` assigns constant `P` the incorrect type `<<e*s,t>,<s,t>`. The expected type is `<e*<s,t>,<s,t>>`.

**Comment by RTKno1** [comment]
This is the expected behavior of the calculator, and will bind * more tightly than implicit commas even if the input type is `constants of type <es*t, st>: P`, which will return `<<e,s*t>,<s,t>>`. We have added brackets around product types as of version 2.6.0 to make this clearer in the calculator. To have implicit commas bind more tightly, the exercise file should be written explicitly as follows: `constants of type <e*<s,t>,st>`.
